### ISSUE TITLE
Native Scrolling with fixed headers flickers in latest Safari

### ISSUE THREAD

**Issue by bentrombley** [handsontable/handsontable#1962]
The issue is clear when I try to scroll on the demo page (http://handsontable.com/demo/scroll.html), using the actual scroll bar or mousewheel to scroll vertically or horizontally.  The header appears to not redraw correctly so it flickers.

Safari is Version 8.0 (10600.1.25.1).  I don't see any such issues in Chrome or Firefox.

**Comment by tikitikifoofoo** [comment]
+1 on this issue. I get flickering on the fixed row/col headers when scrolling in Chrome too.

**Comment by AMBudnik** [comment]
@tikitikifoofoo can you provide more information about flickering on Chrome? I've tried to reproduce it on Chrome 41.0.2272.89 (64-bit) but it worked fine.
@bentrombley I agree, this flickering occurs and after few scrolls fixed row's headers fall 1-2px down. It can be reproduced in Safari 8.0.3 (10600.3.18) also.

**Comment by tikitikifoofoo** [comment]
Hmm... well @AMBudnik, none of my coworkers can duplicate it either, but it's definitely happening on my machine, so I'm not sure what's causing it. I'll let you know if I find out anything more, but I guess don't worry about Chrome for now.

**Comment by AMBudnik** [comment]
OK @tikitikifoofoo if you'll notice something, let us know.

**Comment by krzysztofspilka** [comment]
@tikitikifoofoo this should be fixed with the next release (0.14.0) but please note that it'll introduce a major change to the structure of grid's overlays so your custom CSS, if you have such, will need to be adjusted too.

**Comment by tikitikifoofoo** [comment]
Ok, thanks @krzysztofspilka!

**Comment by jansiegel** [comment]
@tikitikifoofoo, @bentrombley do you still encounter this problem when using the latest ([0.15.0-beta3](https://github.com/handsontable/handsontable/releases/tag/0.15.0-beta3)) version of Handsontable?

We fixed one overlay flickering problem in #2422, but I'm not sure if it is the one you described.

**Comment by csteins** [comment]
It fixed the problem in Chrome for me. But I can still reproduce the error in Safari.

**Comment by tikitikifoofoo** [comment]
@jansiegel this issue is fixed for me on both Chrome and Safari after upgrading to 0.15.0-beta5. Thanks!
