### ISSUE TITLE
Wrong undo/redo behavior after inserting rows/columns

### ISSUE THREAD

**Issue by basvandenberg** [handsontable/handsontable#2743]
When using the context menu to add rows/columns, the undo function correctly removes these rows/columns again. However if you then perform a redo, a different row/column is added. The next undo and redo further messes up the table (1 row/column will be deleted also).

You can test this in the first table on the documentation page: http://docs.handsontable.com/0.16.1/demo-context-menu.html
- Insert a column to the left of column 'B' (column 'B' is empty, the rest shifted right)
- Perform undo and redo (now column 'C' is empty instead of 'B')
- Perform another undo ('B' is empty, one column is deleted)
- Perform another redo (now columns 'B' and 'C' are empty, the one column is still deleted)

**Comment by basvandenberg** [comment]
There seems to be some sort of off-by-one bug that probably also causes the strange behavior described in my previous post.

If I add a column to the right of a table with two columns, the index parameter of the afterCreateCol hook is 2 (the index of the newly added column, this is correct). Performing an undo and redo should result in an afterCreateCol with again index 2, but instead the observed index is 3 in this case.

**Comment by AMBudnik** [comment]
Thanks @basvandenberg, issue related to https://github.com/handsontable/handsontable/issues/1520

**Comment by basvandenberg** [comment]
I fixed this bug and expanded corresponding tests in a feature branch, but when I try to publish this with:

    git flow feature publish issue-2743

I get the following error:

    ERROR: Permission to handsontable/handsontable.git denied to basvandenberg.
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    Switched to branch 'feature/issue-2743'
    Your branch is based on 'origin/feature/issue-2743', but the upstream is gone.
      (use "git branch --unset-upstream" to fixup)

    Summary of actions:
    - A new remote branch 'feature/issue-2743' was created
    - The local branch 'feature/issue-2743' was configured to track the remote branch
    - You are now on branch 'feature/issue-2743'

Am I not allowed to push to the remote? Or is this some issue with my git configurations?

**Comment by AMBudnik** [comment]
Confirmed with [0.24.1](http://docs.handsontable.com/0.24.1/demo-context-menu.html)

**Comment by AMBudnik** [comment]
Another example.

demo: http://jsfiddle.net/mountaineerfan5/pc3x0z6c/

scenario:
![example11](https://cloud.githubusercontent.com/assets/10757813/22638594/5935068e-ec49-11e6-981d-6dcc957e2d05.gif)

**Comment by AMBudnik** [comment]
Similar case

http://jsfiddle.net/v4a6bv5m/
1. Copy few columns
2. Paste them in the last column
3. Undo changes via <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd>

![gi2f](https://cloud.githubusercontent.com/assets/10757813/25802905/c7772aee-33f4-11e7-9928-867b959eeddd.gif)

data is removed by columns are left

**Comment by mountaineerfan5** [comment]
Bug still exists in version 1.15.1:
http://jsfiddle.net/mountaineerfan5/nncvfv2s/4/

1. Remove any combination of columns
2. Undo the remove column change
3. The amount parameter for both the beforeCreateCol and afterCreateCol hook seems to be equal to the index of the right most column deleted

**Comment by AMBudnik** [comment]
Thank you for sharing your feedback @mountaineerfan5

**Comment by AMBudnik** [comment]
It looks like the issue is gone.

I've tested this case

![gif](https://user-images.githubusercontent.com/10757813/38805953-0232de94-4178-11e8-8997-8065726a7d68.gif)

I am closing this issue but if you're still facing any problems or have any doubts let me know.

**Comment by AMBudnik** [comment]
Hi @basvandenberg 

I have good news! We've just released 8.0.0-beta2 that fixes the referenced issue https://github.com/handsontable/handsontable/issues/5000. (We won't be closing that ticket now. It will be closed after we release the final 8.0.0 version of Handsontable)

All feedback's appreciated. I hope that it will also solve your issue.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

@mountaineerfan5 I also encourage you to test 8.0.0-beta2

**Comment by AMBudnik** [comment]
Hi @basvandenberg 

we've just released the official stable version- 8.0.0.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback.
