### ISSUE TITLE
Datapicker without days

### ISSUE THREAD

**Issue by Vertek** [handsontable/handsontable#2931]
Hello, it's possible to delete days from datapicker (type = date) and show only month and years? I need this datapicker but without days

**Comment by AMBudnik** [comment]
Hi @Vertek [here's](http://jsfiddle.net/wy3xhw57/) the example. 

You have to change format for example `dateFormat: 'MM/YYYY'` User will have to click a day of the month but only the MM/YYYY will be shown in you data set.

**Comment by Vertek** [comment]
Yes, i known that but my customer doesn't want have days to pick, only month and year. Days should be completely invisible

**Comment by AMBudnik** [comment]
So the only way is to use a dropdown I guess.

Handsontable uses [Datapicker library](https://github.com/dbushell/Pikaday) and it's just the way its [interface](http://dbushell.github.io/Pikaday/) looks like.

**Comment by budnix** [comment]
Hi @Vertek, 

You can disable days range or all days using `disableDayFn` property like in this [demo](http://jsfiddle.net/0a98uxed/). Handsontable used pikaday as date picker so any options listed [here](https://github.com/dbushell/Pikaday#configuration) should be working.

**Comment by Vertek** [comment]
Hi @budnix 
If i block all days i can't set any data :P, but it's still wrong cuz i see days, i need to have simple pick
Month: xxx
Year: xxx 
and thats all, completely no need to see days

**Comment by AMBudnik** [comment]
@Vertek it'll be better to use dropdown instead. Date is run by Datapicker lib and it's just the way it looks (with those days).

[Example](http://jsfiddle.net/mhog0ezL/). When you have a lot of dates you can create a function that will create you a array to be passed to dropdown source.

**Comment by Vertek** [comment]
Ya, dropdown will be great for that, and i need to create a function which made array with date. I think that i handle it, thanks :)

**Comment by Vertek** [comment]
Last quick question, can i set max data show when i click downdrop? When i have more than 150 elements i array and i click dropdown i need to scroll all table to see what's on bot of dropdown control. I need to see only 5 source, now i see more than 11 and last is cutted.

**Comment by AMBudnik** [comment]
It's as simple as adding [`visibleRows: 5`](http://jsfiddle.net/928ygrye/) to your instance's settings.

**Comment by Vertek** [comment]
doesn't work in instance and even in cellProperties.

**Comment by Vertek** [comment]
https://jsfiddle.net/mhog0ezL/

This demo shows that this function worked but in my project this function doesn't work, what could block it?

**Comment by AMBudnik** [comment]
You mean that `visibleRows: 5` does not work at your project? You would have to create a demo. Without it it's hard to tell what's wrong.

**Comment by Vertek** [comment]
yep, when i write in my hot instance visibleRows: 5 it's doesn't work, when i click on dropdown cell the data is developed to bottom that i can't see end of it so it's doesn't work. My project it's too big to show you demo but if i'm try to check this option in demo with new hot project this work correctly.

**Comment by AMBudnik** [comment]
There's a possibility that other option from your settings is preventing dropdown to appear as it was planned, although it shouldn't be an issue.

To find a solution try to comment parts of instance's settings and disable custom renderers if they run with the dropdown cell.

Looking forward for your investigation clues.

**Comment by Vertek** [comment]
Can i get contact to you? If you're from Poland we could do better communication, because i think that i can't describe problem :/. Git doesn't allow to send priv messages

**Comment by AMBudnik** [comment]
OK, you can email me direcly at [my email](aleksandra.budnik@handsontable.com) and if this problem is related with a HOT issue, the solution will be posted at Github also.
