### ISSUE TITLE
Handsontable Comments reposition while scrolling Vertically - Inside Bootstrap Wrappers

### ISSUE THREAD

**Issue by apatton724** [handsontable/handsontable#4306]
Okay , I've created 2 Gist. The first is 3 hot's wrapped inside of bootstrap wrappers; it works just fine because no scrolling is needed:

http://jsfiddle.net/4xzhqeg3/

The second gist has issues. You'll see that the very first comment works just fine, but any comment that you have to scroll down to get to will not display next to the cell it is for:

http://jsfiddle.net/4xzhqeg3/1/
Hope these examples help.

Thank you guys!

![image](https://cloud.githubusercontent.com/assets/10131238/26412655/78aa0ee2-4077-11e7-8b2d-72721823d6f6.png)

( I initially commented on issue [3081](https://github.com/handsontable/handsontable/issues/3081)   )

**Comment by apatton724** [comment]
bump bump...

Hey @AMBudnik , 

Any Updates or feedback ?  Should I put in a support ticket (Since we have a paid license)?

Thanks guys

**Comment by AMBudnik** [comment]
Hi @apatton724 

sorry for keeping you waiting. I will check the example today and let you now about next steps no later than tomorrow.

**Comment by apatton724** [comment]
Thank you :) @AMBudnik

**Comment by AMBudnik** [comment]
I can see that the issue has been fixed by one of our devs in a newer version. Please check the updated code http://jsfiddle.net/nbyt8ukr/

**Comment by apatton724** [comment]
Nice! So just download the latest version of Handsontable and I should be good to go?

**Comment by AMBudnik** [comment]
Yes. But please notice that we have also changed the way you declare a comment. Now you should pass it as an object

`comment: {value: 'Hello world!'}`

**Comment by apatton724** [comment]
Gotcha. Thank you. I will upgrade today and update the comment section as well and then give it all a shot.

**Comment by apatton724** [comment]
I've upgraded and I'm still getting the same issue. I'm now starting to think that the issue isn't Bootstrap. It may be Aurelia. If you're familar with it,  you know that you can create  "components" which are just stand alone html files that you can pass from page to page so you don't have to create those components over and over again. I think the <compose> wrapper may be the culprit. I'll work on a jsfiddle....

**Comment by AMBudnik** [comment]
As I have checked the issue history there were two other Clients who have tried to integrate Handsontable with Aurelia, unfortunately, they both failed. Though I do not have any details about the case.

**Comment by apatton724** [comment]
@AMBudnik , 
Thank you for that bit of information.  Besides the comments, Handsontable has been working flawlessly with Aurelia. I hope those others have not given up. I will check to see if I can find those issues and help them out.

**Comment by AMBudnik** [comment]
One of the Clients has already written that he has chosen other library (did not mention which one), but maybe there's someone besides Github or our Forum that is looking for an answer.

ps. thank you for the kind words :) It is very nice to hear that even if Handsontable is not perfect it is something that is helping our Clients to accomplish their goals.

**Comment by apatton724** [comment]
You are more than welcome.  I appreciate the work you guys are putting into this. I haven't met a perfect piece of software yet...all we can do as developers is our best. Take care.

**Comment by umagon** [comment]
I'm still getting the issue. I discovered someone that has fixed it locally. Maybe it's of help.

https://forum.handsontable.com/t/comment-positioning-wrong-when-hot-inside-any-scrolling-region/774/4
