### ISSUE TITLE
TrimRows plugin breaks expected startRows behaviour

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#5953]
### Description
When we initialise Handsontable without initial data but with enabled TrimRows, then standard behaviour of the `startRows` is broken - an instance doesn't render any rows.

Although, `TrimRows` plugin enabled in `updateSettings` works well.

### Steps to reproduce
1. Initialise an instance without `data`  but with `trimRows: true`.

### Demo
https://jsfiddle.net/zc5ybdt3/

### Your environment
* Handsontable version: 1.14.0+ (perhaps even older)
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
The issue stays the same after introducing changes to #5751 on the branch https://github.com/handsontable/handsontable/tree/feature/issue-5751.
Tested on Chrome 76/ macOS Mojave / local server.

The table still does not load rows. There are no additional errors.

**Comment by aninde** [comment]
@AMBudnik  I'm testing v8.0-rc1 and looks like the issue is solved. 
Demo
original issue: https://jsfiddle.net/zc5ybdt3/

Version 8.0.0rc https://jsfiddle.net/aninde/7mk9fjx5/

Environment
Handsontable version:8.0.0.rc

Browser Name and version: Google Chrome version 76.0.3809.100
Operating System: macOS Mojave 10.14.6

**Comment by aninde** [comment]
This issue should be fixed after realising new version. We are currently testing a version with many breaking changes, I recommend observing information from issue [#5751.](https://github.com/handsontable/handsontable/issues/5751)

**Comment by AMBudnik** [comment]
Yup, confirmed @aninde works well with the never branch

**Comment by AMBudnik** [comment]
Example updated to 8.0.0-beta1 https://jsfiddle.net/opv9w2nz/ working well

**Comment by AMBudnik** [comment]
And the official v 8.0.0 https://jsfiddle.net/opv9w2nz/ where the issue remains solved.
