### ISSUE TITLE
[New feature request] Infinite scroll

### ISSUE THREAD

**Issue by andrescardona** [handsontable/handsontable#607]
Hi, I think that this would be a nice feature, for example i'm having issues bringing a big amount of data, the number of objects that i have to create in order to provide the complete dataset to the tables is so big that the browser just crashes, the virtual rendering works smoothly but a partial data retrieval mechanism would be needed in many cases.

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by ashwinrayaprolu1984** [comment]
I updated the plugin create by @marcsch 
https://gist.github.com/marcsch/c8317978e1d26bf049bb

and created a new jsFiddle

http://jsfiddle.net/ashwin_rayaprolu/r9pn62bu/

**Comment by hristod** [comment]
Hey, guys. Anyone tried @ashwinrayaprolu1984 's solution on the new version? I am trying to use it but I keep getting "cb is not a function" and it doesn't work...

**Comment by basrita** [comment]
Hi  guys,I have used  @ashwinrayaprolu1984 's solution.It is working but i am facing the issue that column freezing is not working properly. If i removed the plugin it is plugin.please help me in this regard as we have crucial deliverable.

**Comment by marcsch** [comment]
You may also try out my [updated solution](https://gist.github.com/marcsch/c8317978e1d26bf049bb). Adding 'fixedColumnsLeft: 2' to the [jsFiddle example](http://jsfiddle.net/7Z3bD/49/) seems to work fine.

**Comment by basrita** [comment]
When i keep manualcolumnfreeze option true it is not  freezing the particular column it is freezing the starting column.still the same problem exists when i have tried with your plugin.even i have tried in your jsfiddle example.
Thanks.

**Comment by marcsch** [comment]
I see the problem now. Columns are being freezed, but always the leftmost, not the one that was intended to be freezed. This might be due to the fact that the plugin keeps the data in it's own array, which is handed over to Handsontable using `loadData` at each page load event. I can't deliver you an immediate solution as I'm not that familiar with how column freezing works.

**Comment by basrita** [comment]
ok @marcsch . Thanks for your reply.please fix the issue.

**Comment by marcsch** [comment]
@basrita: Manual column freezing and also manual reordering [should work now](https://gist.github.com/marcsch/c8317978e1d26bf049bb). You can test it [here](http://jsfiddle.net/7Z3bD/54/) (just uncomment the `manualColumnFreeze` option).
Be aware that any adding/removing rows and columns will not work with this plugin as stated above.

**Comment by basrita** [comment]
@marcsch :  how to perform freezing then because no "freeze column" option is not there.

**Comment by basrita** [comment]
Thanks @marcsch . It is working now.

**Comment by basrita** [comment]
Hi guys,

I am facing an issue in this.

I am calling my own function in the getPage() .
In my function i wrote one http call.

It is working fine for me but the problem is with out getting the response from 1st request 2nd and 3rd requests are calling.I don't know why it is happening due to delay or some thing else.
I don't want this behavior in my application. 

please help me in this regard.

Thanks in advance.

**Comment by marcsch** [comment]
@basrita: I'm sorry, but I'm not sure I understand the problem. Did you modify the `getPage()` function?

Did I understand it correctly, there is no response to your HTTP request? While scrolling, it is easily possible that multiple requests are done within a short time, so the first one does not have to be completed in order for the others to be initiated, the grid is filled with data as soon as a request is completed. Did you check if your request completes without errors? Do you execute the `cb` function as in[ this example](https://gist.github.com/marcsch/c8317978e1d26bf049bb#file-lazyloader-js-L10)?

I hope I got your problem, otherwise you might explain it again, maybe with example code.

P.S. you can also comment [here](https://gist.github.com/marcsch/c8317978e1d26bf049bb). I have also been thinking about transforming the jsFiddle into a repository, so that could be discussed in a separate issue.

**Comment by basrita** [comment]
Hi @marcsch 

I am facing another issue in infinite scrolling.

The alignment which is applied for particular column is getting cleared when scroll down.I think some configuation i am missing.

can you please help me in this regard.

Thanks in advance.

**Comment by marcsch** [comment]
@basrita
Unfortunately, I can't reproduce the problem, do you apply the alignment manually to that column by right clicking? That seems to work, at least [here](http://jsfiddle.net/7Z3bD/83/). Could you otherwise give me some example code or tell me the steps to reproduce it?

**Comment by basrita** [comment]
Hi @marcsh,

Thank you for your reply.
I your example it is reproducing that.
I need to see that i have done any mistake as it is producing in my case.
If i am unable to find it i will share my example so that you cal help me.

Thank you.

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
