### ISSUE TITLE
Bug when scrolling over a dozen cells right with Comments and fixedColumnLeft turned on.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6188]
### Description
We have a bug - `Uncaught TypeError: Cannot read property 'defaultView' of undefined` when we have both plugins turned up and scrolling over a dozen cells right.

### Steps to reproduce
1. Open a console.
2. Scroll horizontally to `Z`
3. Hover over cell `0,0`.
![Kapture 2019-08-07 at 13 59 50](https://user-images.githubusercontent.com/1555809/62621233-b006c500-b91b-11e9-8ae1-4f35741f2353.gif)

### Demo

https://jsfiddle.net/kw2eaqhf/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by warpech** [comment]
Might be caused by the same problem as #6043 or #6191

**Comment by AMBudnik** [comment]
Fixed with the `7.2.0`. Updated demo https://jsfiddle.net/handsoncode/bujmnhf3/

**Comment by rbgada23** [comment]
@AMBudnik - The updated demo still reproduces the same bug. The issue is still open

**Comment by AMBudnik** [comment]
Thank you for noticing @rbgada23 

I was able to get the same error with 7.2.0 and (the latest) 8.2.0 
https://jsfiddle.net/c3op5m62/1/
![image](https://user-images.githubusercontent.com/10757813/101741105-f1882100-3ac9-11eb-88bb-cb607ea0aac5.png) 
Now tested on Windows 10, Chrome 87

**Comment by AMBudnik** [comment]
Hi @charlie0228 I tested our `width`/`height` and `viewportColumnRenderingOffset` and none of them have any impact on the issue. (I've already tested the Handsontable v11.1 https://jsfiddle.net/wmne46xj/4/) 
I will, however, update you as soon as we fix it.

**Comment by charlie0228** [comment]
@AMBudnik
Thanks for your reply and your help, but there is still have another issue related to it.
When column A is fixed, then scroll view to column C and hover to A1.
The comment will be displayed in the wrong position.
Here's the reproduction screenshot.

![feb-11-2022_18-06-05](https://user-images.githubusercontent.com/24387287/153883033-7f0e2336-a05a-48b2-bd12-09bbf56d0965.gif)

Once again, thank you very much for your help.

**Comment by AMBudnik** [comment]
@charlie0228 

as my colleague mentioned here https://github.com/handsontable/handsontable/issues/4389#issuecomment-767620440 this is the same issue as reported at https://github.com/handsontable/handsontable/issues/6744 for the comment position on scroll

**Comment by AMBudnik** [comment]
@charlie0228 

we just fixed the origin issue https://github.com/handsontable/handsontable/issues/9645 in Handsontable v12.3.0
please update and let me know if everything works well for you
