### ISSUE TITLE
The unfreeze column fails to process successfully when rowHeaders equal to false

### ISSUE THREAD

**Issue by miwoy** [handsontable/handsontable#6797]
### Description

When I use the freeze function and set rowHeaders equal to false, the unfreeze column fails to process successfully. Column is still fixed on the left

### Demo

https://jsfiddle.net/zx97b3dk/1/

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Google Chrome v80.0.3987.149
* Operating System: macOs 10.15.4

**Comment by AMBudnik** [comment]
Thank you for sharing this issue report @miwoy 

#### Freezing
Here's one of our tests https://github.com/handsontable/handsontable/blob/ca1ab950de4522bdb899f9e442cef978d860685e/src/plugins/manualColumnFreeze/test/manualColumnFreeze.e2e.js#L24

where we define that the column should be frozen even when `rowHeaders` is not a part of the Handsontable settings.
And it works well https://jsfiddle.net/AMBudnik/17y9km3f/

And it also works if we freeze the column manually
https://jsfiddle.net/AMBudnik/c7yxmurd/
![Zrzut ekranu 2020-04-1 o 09 26 40](https://user-images.githubusercontent.com/10757813/78110286-f359fa80-73fa-11ea-9cf3-c94eb1376420.png)

#### Unfreezing
However, unfreeze produces some unexpected behavior
![Zrzut ekranu 2020-04-1 o 09 28 04](https://user-images.githubusercontent.com/10757813/78110381-2603f300-73fb-11ea-860b-fcf72246ad24.png)

It looks like there is a different method for unfreezing the columns programmatically and manually.

Unfreezing columns programatically works well.
https://github.com/handsontable/handsontable/blob/ca1ab950de4522bdb899f9e442cef978d860685e/src/plugins/manualColumnFreeze/test/manualColumnFreeze.e2e.js#L52
https://jsfiddle.net/AMBudnik/pLjagw93/ 
__________
Tested on OS Catalina / Chrome 83

**Comment by miwoy** [comment]
I don't think my problem has been solved. 
It seems normal to use the freezeColumn function, but it doesn't work properly when using the Unfreeze Column of ContextMenu. 
That's right, the fixedColumnsLeft value is correct, but it was not processed normally when displayed. 
Please use ContextMenu to operate it in https://jsfiddle.net/zx97b3dk/1/

like it.


![Kapture 2020-04-01 at 16 27 13](https://user-images.githubusercontent.com/6166336/78115692-c0812800-7435-11ea-81f0-3a9f7fb149f2.gif)

**Comment by miwoy** [comment]
And colHeader does not seem to handle correctly when Freeze Column @AMBudnik

**Comment by AMBudnik** [comment]
> I don't think my problem has been solved.

I agree. I have marked it as a bug.
I just wrote that it works when you use the method from the plugin - doing unfreezing manually is broken.

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/o5uLfvpy/

**Comment by AMBudnik** [comment]
The issue works the same in Handsontable v12.1.3 - https://jsfiddle.net/xbg4d517/ updated demo
