### ISSUE TITLE
[9.0.0] Can't block autofill via `beforeChange` when using formulas

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8107]
### Description

We are not able to block autofill when formulas are defined.

The issue should be fixed after https://github.com/handsontable/hyperformula/pull/678

The issue does not occur when
* we use v8.4.0 https://jsfiddle.net/gp2ne5qz/2/
* we comment out formulas

### Steps to reproduce

1. Autofill `A1` to `A2`

**Result in v8.4.0 and v9 without formulas**
Cell `A2` does not change its value - we still have `2017` in the cell. 

**Result in v9 with formulas enabled**
Cell `A2` changes its value - we have `2016` in the cell. 

### Demo

https://jsfiddle.net/xc5gqLn1/4/

### Your environment
* Handsontable version: v9+
* Browser Name and version: Chrome 89
* Operating System: Windows 10

_Test Zen 26993 after fix_

**Comment by Siemienik** [comment]
Actually, Enabling the HyperFormula causes that we cannot prevent change the value:

With HF:
![May-28-2021 08-51-08](https://user-images.githubusercontent.com/2893099/119942238-dfc00a80-bf91-11eb-95fc-6468a5a4cdef.gif)

Without:
![May-28-2021 08-51-27](https://user-images.githubusercontent.com/2893099/119942279-ea7a9f80-bf91-11eb-818e-ab1b6a57d85f.gif)


```js
const container = document.getElementById('container');
    const hot = new Handsontable(container, {
      data: [
        [1, 999, 3, '=B1*500', '=B1*5'],
        [9, 8, 7, '=B2*500', '=B2*5'],
        [4, 6, 2, '=B3*500', '=B3*5'],
      ],
      type: 'numeric',
      rowHeaders: true,
      colHeaders: true,
      // formulas: {
      //   engine: HyperFormula
      // },
      beforeChange(changes, source) {
        changes[0] = null;
      }
    });
```

**Comment by nikersify** [comment]
The problem seems to be related to the fact that we're hooking up to `beforeChange` in the formulas plugin, the callback to which will always run before any user defined hook. It used to be the case that the plugin used to work with `modifyData` instead before https://github.com/handsontable/handsontable/pull/7648/commits/e8a8249832e22ab43dd4c387d53073ba47aac4fb, and it seems like the bug above didn't exist before that commit.

**Comment by nikersify** [comment]
#8134

**Comment by nikersify** [comment]
Looks like the problem from https://github.com/handsontable/handsontable/issues/8107#issuecomment-850190427 was fixed in https://github.com/handsontable/handsontable/pull/8139, I'm changing the title back to the original one related to autofill only.

**Comment by wojciechczerniak** [comment]
@nikersify Isn't it fixed in #8129?

**Comment by nikersify** [comment]
I get an error every time I try to autofill using the latest build from that PR (005337161) 🤷

**Comment by nikersify** [comment]
@wojciechczerniak never mind, I tested the commit (https://github.com/handsontable/handsontable/pull/8129/commits/fecc19b45b9a4e5282310d94317203207c34d17d) before the one that prepares for hyperformula@1.0 - I don't get an error anymore but this issue is not fixed by those changes.

**Comment by wojciechczerniak** [comment]
Ok. So this is a first good step, we will have data in `beforeChange` from HF, but we still use `beforeChange` to sync the changes with HF

**Comment by aninde** [comment]
This issue will be fixed by v10 https://jsfiddle.net/9h0soLvu/.

**Comment by AMBudnik** [comment]
Issue closed as fixed in v10
